---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: database
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      serviceAccountName: ado-dashboard-secrets-manager
      securityContext:
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets
        - name: postgres-config
          configMap:
            name: postgres-config
            defaultMode: 0755
      containers:
        - name: postgres
          image: case.artifacts.medtronic.com/ext-docker-remote/postgres:16-alpine
          command: ["/scripts/entrypoint.sh"]
          ports:
            - name: postgres
              containerPort: 5432
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: secrets-store-inline
              mountPath: /config
              readOnly: true
            - name: postgres-config
              mountPath: /scripts/entrypoint.sh
              subPath: entrypoint.sh
            - name: postgres-config
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
