---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ado-dashboard

labels:
  - pairs:
      app: ado-dashboard

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - secrets-provider.yaml
  - serviceaccount.yaml
